version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: 
              name: install-dependencies
              command: npm install
          - run: 
              name: tests
              command: npm test
  build-prod:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP ./build_project.sh
  deploy-prod:
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP ./deploy_project.sh
workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - build-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
      - deploy-prod