version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm test
  deploy-prod:
    docker:
      - image: circleci/node:13.6
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_project.sh”
workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy-prod:
        filters:
          branches:
            only:
              - master
        requires:
          - build